# Generated by Django 4.2.6 on 2023-11-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('description', models.TextField(max_length=500)),
                ('tags', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='news_app/media')),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
